name: NFPC NFTC Weekly Check (No API)

on:
  schedule:
    - cron: "0 5 * * 5"  # 매주 금요일 14:00 KST = 05:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run checker (no api)
        run: |
          python scripts/check_updates_noapi.py

      - name: Commit & push
        run: |
          git config user.name "nfpc-nftc-bot"
          git config user.email "bot@users.noreply.github.com"
          git add data.json snapshot.json reports/*.html || true
          git commit -m "Weekly NFPC/NFTC check" || echo "No changes"
          git push
